### ISSUE TITLE
Something is wrong with the padding on most elements

### ISSUE THREAD

**Issue by draav** [heroes-coding/Heroes-Report#1]
Sites is really cool, but impossible to read in my browser. Is it meant to look like this, or is there something wrong on my end.

[Here is an image](https://imgur.com/a/zbykuMD?) i put red boxes around some areas that are misaligned or are missing padding or runout of space or are overlayed or whatever. they're obvious but ya never know.

**Comment by heroes-coding** [comment]
Hey Draav - sorry, didn't notice this until now.  Site doesn't have those display issues (aside from the percentage cutoffs on the win rate graph, an auto tick making problem; I'll need to set the overflow for that svg properly) for me in Firefox or Chrome.  Can you let me know what browser you are using?  (Although I'm not going to try and support any other browsers; still curious)

EDIT:  So I reproduced the issue by selecting large fonts in Chrome.  This isn't something I have time to dig into the nitty gritty of css to fix as it is a big pain for me; if you want to see larger it without most of those issues just select medium fonts and scale up with Ctrl-+
